project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "AgEc 211"
  favicon: "plot/agec211-hex-logo.png"
  
  repo-url: https://github.com/agec211-stat-methods/agec211-site
  site-url: https://agec211-stat-methods.github.io/agec211-site/
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/agec211-hex-logo.png"
    contents:
      - href: "index.qmd"
        text: "Home"
      - section: "Topics"
        contents:
          - href: "m1-intro-r.qmd"
            text: "Module 1: Intro to R programming"
          - href: "m2-intro-dataviz.qmd"
            text: "Module 2: Intro to data viz using ggplot2"
          - href: "m3-reproducible-report.qmd"
            text: "Module 3: Reproducible reports with Quarto"
          - href: "m4-eda.qmd"
            text: "Module 4: Exploratory data analysis (EDA)"
          - href: "m5-tests-on-means.qmd"
            text: "Module 5: Tests on means"
          - href: "m6-correlations.qmd"
            text: "Module 6: Correlations"
          - href: "m7-regression.qmd"
            text: "Module 6: Multiple regression analysis"



format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual
